### ISSUE TITLE
Question: How to merge audio&video files (mux) so that the audio will loop if needed? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [umair13adil/KotlinFFMpeg#11]
Using this library (or others), is it possible to merge audio&video together, so that the output video will be of the same duration as the input video, and have the audio loop if it's shorter than the video?

I've asked about it here too:
https://stackoverflow.com/q/54769976/878126

**Comment by AndroidDeveloperLB** [comment]
I tried to use this:
https://superuser.com/a/1319950/152400

by writing this in `AudioVideoMerger` class:

        val cmd = arrayOf("-i", video!!.path,"-filter_complex","\"amovie=${audio!!.path}:loop=0,asetpts=N/SR/TB[aud];[0:a][aud]amix[a]\"","-c:v","copy","-c:a","aac","-b:a","256k","-shortest",outputLocation.path)

but it failed with this error in the log:

`
 [AVFilterGraph @ 0xea5d1280] No such filter: '"amovie'
 Error initializing complex filters.
 Invalid argument
     at com.blackbox.ffmpeg.examples.tools.video.AudioVideoMerger$merge$1.onFailure(AudioVideoMerger.kt:85)
     at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.onPostExecute(FFmpegExecuteAsyncTask.java:70)
     at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.onPostExecute(FFmpegExecuteAsyncTask.java:10)
     at android.os.AsyncTask.finish(AsyncTask.java:695)
     at android.os.AsyncTask.access$600(AsyncTask.java:180)
     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:193)
     at android.app.ActivityThread.main(ActivityThread.java:6718)

2019-02-24 17:46:20.727 23712-23712/com.blackbox.ffmpeg.examples W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

**Comment by AndroidDeveloperLB** [comment]
Never mind, got it:

        val cmd = arrayOf("-i", video!!.absolutePath, "-stream_loop", "-1", "-i", audio!!.absolutePath, "-c:v", "copy","-c:a","copy", "-map", "0:v:0", "-map", "1:a:0", "-shortest", outputLocation.absolutePath)

It works really well, but for some reason the sample project can't play the output file.

How come?

If I remove the `"-c:a","copy"` , it will succeed playing, but also will take a long time to make the file...
